### ISSUE TITLE
What happens if I use this library with iOS?

### ISSUE THREAD

**Issue by ZeroCho** [Raja0sama/rn-foreground-service#1]
I'm currently making an app for android and iOS.
I found out that this library doesn't have any iOS related code.
What happens if I use this library with iOS?
Does nothing without any error or break an app?

**Comment by Raja0sama** [comment]
There is no foreground state in ios, so no foreground service for that. As
far as error is concerned, we have implemented platform checks if you still
get any error make sure to implement from your end as well.

**Comment by adirzoari** [comment]
@ZeroCho did you find any solution for IOS?
@Raja0sama

**Comment by hupptechnologies** [comment]
@adirzoari This is not possible in iOS, foreground service is only feature of the android OS.
