### ISSUE TITLE
node_modules/@supersami/rn-foreground-service/postinstall.js   overwrites the existing resource in colors.xml.

### ISSUE THREAD

**Issue by AnantTiwari001** [Raja0sama/rn-foreground-service#101]
When running node node_modules/@supersami/rn-foreground-service/postinstall.js in an existing project that has items in colors.xml and the app depends on it for instance a new expo project. The existing resources are removed/ overwritten.

**Comment by Raja0sama** [comment]
Please retry, i just released a new version.
