### ISSUE TITLE
registerHeadlessTask or registerCancellableHeadlessTask called multiple times

### ISSUE THREAD

**Issue by hondem** [Raja0sama/rn-foreground-service#11]
Seems like there is an issue with repeatedly registered tasks (caused by `ReactNativeForegroundService.register()`). Could this potentially lead to some issues?

![Screenshot 2021-05-06 at 14 58 27](https://user-images.githubusercontent.com/17029828/117302037-84f82f00-ae7b-11eb-8cfd-16fbc8ac6b57.png)

**Comment by adasilvapdev** [comment]
I'm having this same issue too.

![image](https://user-images.githubusercontent.com/20091777/117717234-90639700-b1a8-11eb-97f0-94a5c0c55b59.png)
