### ISSUE TITLE
Cannot read property 'startService' of undefined

### ISSUE THREAD

**Issue by prezpl** [Raja0sama/rn-foreground-service#13]
Hi,
I am following your installation process but somehow I am still getting this error. 
I have appended AndroidManifest.xml, mainActivity.java, colors.xml and then registered and started the task. When I open the debugger, I can see the log in the console saying **Start Service triggered**, but then I am getting **TypeError: Cannot read property 'startService' of undefined** shortly after. Could you help me to get this working, please?

**Comment by Anudnya93** [comment]
Hi @pprzewloka , How did you resolved it ?

**Comment by pprzewloka** [comment]
Hi, as far as I remember using Expo was the main issue. To make it work, I had to create my project using react native CLI, if I'm not mistaken.

**Comment by Anudnya93** [comment]
ok, so was it working in react native cli ? Because I am using it in react native cli and it is returning me empty object for ReactNativeForegroundService.

**Comment by pprzewloka** [comment]
> ok, so was it working in react native cli ? Because I am using it in react native cli and it is returning me empty object for ReactNativeForegroundService.
> 


Yes, it was working perfectly with React Native CLI, although it was quite a bit ago, some things may have changed, or you might have done a small mistake. I remember I followed the installation guide and it worked.

**Comment by Anudnya93** [comment]
ok, let me check again. Thanks for quick responses.

**Comment by dbwhdtjr0457** [comment]
Hi @Anudnya93 , I'm having a same issue here. I've tried with expo, create-react-native-app and React Native CLI and nothing seems to work. Could you tell me how you solved it?

**Comment by Salmankhan033** [comment]
It occurs on IOS. 
How to resolve it ?

**Comment by Salmankhan033** [comment]
How we will do in IOS?

> Hi @dbwhdtjr0457 @Salmankhan033. This has android module only. It can not work on iOS.
Any other library to fetch services in app background mode ?
