### ISSUE TITLE
How can i remove the foreground service after the app is killed ? 

### ISSUE THREAD

**Issue by Tratt0re** [Raja0sama/rn-foreground-service#17]
I need only to do some operation while the app is in background , when the app is killed i need to to kill the foreground service too. Is this possible ? How can i achieve  that ?

Thanks a lot

**Comment by Raja0sama** [comment]
Yes, it is possible, you can just kill the foreground on the unmount, so if your app is in the background, the component isn't unmounted yet, but if you kill the app from the recent apps, it will kill the service.
