### ISSUE TITLE
service stops while phone screen off

### ISSUE THREAD

**Issue by suraj7370** [Raja0sama/rn-foreground-service#18]
Hello i am using this library for update live location this works fine when phone is awake but after phone sleep(screen off) foreground service stops. is there any solution for foreground service keep running while phone screen is off. 
my index.js file, location.js and MainActivity.java files are listed below:

**......................index.js.................................**
` import ReactNativeForegroundService from "@supersami/rn-foreground-service";

import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';
import { bgMessage } from './src/notifications/FirebaseNotification';

AppRegistry.registerComponent(appName, () => App);
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessage)
ReactNativeForegroundService.register();
ReactNativeForegroundService.start({
  id: 144,
  title: "location Service running",
  message: "you are online!",
});` 

**........................................location.js..........................................................**
`import React, { Component } from 'react';
import {
  Alert, DeviceEventEmitter, Linking,
  PermissionsAndroid, Platform, View
} from 'react-native';
import AndroidOpenSettings from 'react-native-android-open-settings';
import Geolocation from 'react-native-geolocation-service';
// const Geolocation = Platform.OS == "android" ? require("react-native-geolocation-service") : require("@react-native-community/geolocation")
import { PERMISSIONS, request, requestMultiple } from 'react-native-permissions';
import { connect } from 'react-redux';
import * as Actions from '../../redux/actions/index';
import Constants from '../StringConstants';
import BackgroundTimer from 'react-native-background-timer';
import ReactNativeForegroundService from '@supersami/rn-foreground-service';

class WatchLocationBackground extends Component {
  constructor(props) {
    super(props);
    this.state = {
      agree: false,      
    };    
  }
  
  componentDidMount = () => {
    DeviceEventEmitter.addListener(Constants.WATCH_LOCATION, this.startWatchLocation,);
    DeviceEventEmitter.addListener(Constants.CANCEL_WATCH_LOCATION, this.clearWatchLocation,);
    //this.startWatchLocation();
  };

  componentWillUnmount = () => {
    DeviceEventEmitter.removeListener(Constants.WATCH_LOCATION, this.startWatchLocation,);
    DeviceEventEmitter.removeListener(Constants.CANCEL_WATCH_LOCATION, this.clearWatchLocation,);
  };

  /*removeLocationUpdates = () => {
    this.clearWatchLocation();
  };*/

  startWatchLocation = () => {
    let { isLogin, user, OnlineStatus } = this.props;
    if (isLogin && user && user.status && user.status == 'Active') {//
      if (!this.props.hasPermission) {
        Alert.alert(
          "Use your location",
          '' + "This app collects location data to enable live tracking feature even when the app is in background or not in use." + '',
          [
            {
              text: "OK",
              onPress: () => this.requestPermissions(),
            },          
          ],
          { cancelable: false },
        );
      } else {
        this.requestPermissions(); 
      }
    } else {
      this.clearWatchLocation();
    }
  };

  requestPermissions = async () => {
    if (Platform.OS === 'ios') {
      Geolocation.requestAuthorization('whenInUse');
      Geolocation.setRNConfiguration({
        skipPermissionRequests: false,
        authorizationLevel: 'whenInUse',
      });
      this.startGettingLocation();
    }

    if (Platform.OS === 'android') {    
      let permission = await PermissionsAndroid.requestMultiple([
        PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
        PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION,]

      );
      
      console.log('permission found:--' + permission['android.permission.ACCESS_BACKGROUND_LOCATION']
       + permission['android.permission.ACCESS_FINE_LOCATION']);
      if (permission['android.permission.ACCESS_BACKGROUND_LOCATION']=='granted'
       && permission['android.permission.ACCESS_FINE_LOCATION'] == 'granted'
      ) {
        //this.getLocation();
        this.props.permissionGranted(true);
        this.startGettingLocation();
      } else {
        const result = await requestMultiple([PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
                  PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION,]
          );
      
        console.log('result:--' + JSON.stringify(result));
        //this.getLocation();
        //this.props.permissionGranted(true);
        this.startGettingLocation()
      }
    }
  };

startGettingLocation= () => {
  ReactNativeForegroundService.add_task(() => {
    if (Platform.OS === 'ios') {
            this.getIosLocation();
          } else {
            this.getLocation();
          }
  }, {
    delay: 10000,
    onLoop: true,
    taskId: 'taskid',
    onError: (e) => console.log(`Error logging:`, e),
  });
  
}

  stopGettingLocation = () => {
    try {
      BackgroundTimer.clearInterval(this.timer);
    }
    catch (e) {
      console.log(e)
    }
  }

  getLocation = () => {
    let { user } = this.props;
    console.log("Getting Location")
    Geolocation.getCurrentPosition(
      (position) => {
        console.log("position", position)
        if (user && user.status == 'Active') {
          this.props.saveLocation(position.coords);
          this.props.updateLocation(position.coords);
        } else {
          this.removeLocationUpdates();
        }
        //console.log('watch location fetched:---' + JSON.stringify(position));
        //console.log('this.watchID' + this.watchID);
        // alert("watch location fetched:---" + JSON.stringify(position));
      },
      (error) => {
        // See error code charts below.
        //console.log('this.watchID' + this.watchID);
        console.log(error.code, error.message);
        //Alert.alert('', 'watch location error:---' + JSON.stringify(error));
        this.requestPermissions();
      },
      {
        enableHighAccuracy: true,
        //distanceFilter: 0, // Minimum displacement between location updates in meters
        //interval: 5000, // Interval for active location updates (android only) in ms
        showLocationDialog: true, // whether to ask to enable location in Android (default true)
        //useSignificantChanges: true, // Uses the battery-efficient native significant changes APIs to return locations. Locations will only be returned when the device detects a significant distance has been breached (iOS only)
        timeout: 15000,
        maximumAge: 10000,
      },
    );
  };

  getIosLocation = () => {
    let { user } = this.props;
    Geolocation.getCurrentPosition(
      (position) => {
        if (user && user.status == 'Active') {
          this.props.saveLocation(position.coords);
          this.props.updateLocation(position.coords);
        } else {
          this.removeLocationUpdates();
        }
        // alert("watch location fetched:---" + JSON.stringify(position));
      },
      (error) => {
        // See error code charts below.
        //console.log('this.watchID' + this.watchID);
        console.log(error.code, error.message);
        //Alert.alert('', 'watch location error:---' + JSON.stringify(error));
        this.requestPermissions();
      },
      {
        enableHighAccuracy: true,
        //distanceFilter: 0,
        //interval: 2000,
        showLocationDialog: true,
        //useSignificantChanges: true,
        timeout: 15000,
        maximumAge: 10000,
      },
    );
  };

  requestAlert = (data) => {
    let messsage =
      'Please check or change the location permission, we need rider location to track the bookings.';
    const isIOS = Platform.OS == 'ios';
    Alert.alert(
      '',
      data ? data : messsage,
      [
        {
          text: 'CANCEL',
          onPress: () => console.log('Cancel Pressed'),
          style: 'cancel',
        },
        {
          text: 'CHECK',
          onPress: () => {
            if (isIOS) {
              // this.requestPermissionIos();
              Linking.canOpenURL('app-settings:')
                .then((supported) => {
                  if (!supported) {
                    console.log("Can't handle settings url");
                  } else {
                    Linking.openURL('app-settings:');
                  }
                })
                .catch((err) => console.error('An error occurred', err));
            } else {
              // AndroidOpenSettings.locationSourceSettings();
              AndroidOpenSettings.appDetailsSettings();
            }
          },
        },
      ],
      { cancelable: false },
    );
  };

  clearWatchLocation = () => {
      //console.log('clearWatchLocation:' + this.watchId);
      this.stopGettingLocation();
  };

  render() {
    return (
      <View></View>
    );
  }
}

const mapStateToProps = (state) => {
//  console.log(state.userDataReducer.state)
  return {
    isLogin: state.isLoginReducer,
    user: state.userDataReducer,
    OnlineStatus: state.driverOnlineStatusReducer,
    hasPermission: state.permissionGrantedReducer
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    saveLocation: (data) => dispatch(Actions.saveLocation(data)),
    updateLocation: (data) => dispatch(Actions.updateLocation(data)),
    permissionGranted: (data) => dispatch(Actions.permissionGranted(data)),
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(WatchLocationBackground);
`

**.......................................MainActivity.java...........................................**
`package com.garrud.dev;

import android.annotation.SuppressLint;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

import org.devio.rn.splashscreen.SplashScreen;

import android.content.Intent;
import android.util.Log;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.modules.core.DeviceEventManagerModule;

public class MainActivity extends ReactActivity {

   @Override
  protected void onCreate(Bundle savedInstanceState) {
//    SplashScreen.show(this, R.style.MySplashTheme);
     setTheme(R.style.AppTheme); // Now set the theme from Splash to App before setContentView
     setContentView(R.layout.launch_screen); // Then inflate the new view
     SplashScreen.show(this); // Now show the splash screen. Hide it later in JS
    super.onCreate(savedInstanceState);
  }

   @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "GarrudTransporter";
  }

  // @Override
  // public void onNewIntent(Intent intent) {
  //   super.onNewIntent(intent);
  //   setIntent(intent);
    
  // }

  public void createNotificationChannel() {

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      CharSequence name = getString(R.string.default_channel);
      String description = "This shows Notifications";
      int importance = NotificationManager.IMPORTANCE_MAX;
      @SuppressLint("WrongConstant") NotificationChannel channel = new NotificationChannel(getString(R.string.default_channel), name, importance);
//            channel.setDescription(description);
      NotificationManager notificationManager = getSystemService(NotificationManager.class);
      if (notificationManager != null) {
        notificationManager.createNotificationChannel(channel);
      }
    }
  }
  public boolean isOnNewIntent = false;

  @Override
  public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    setIntent(intent);
    isOnNewIntent = true;
    ForegroundEmitter();
  }

  @Override
  protected void onStart() {
    super.onStart();
    if(isOnNewIntent == true){}else {
        ForegroundEmitter();
    }
  }

  public  void  ForegroundEmitter(){
    // this method is to send back data from java to javascript so one can easily
    // know which button from notification or the notification button is clicked
    String  main = getIntent().getStringExtra("mainOnPress");
    String  btn = getIntent().getStringExtra("buttonOnPress");
    WritableMap  map = Arguments.createMap();
    if (main != null) {
        map.putString("main", main);
    }
    if (btn != null) {
        map.putString("button", btn);
    }
    try {
        getReactInstanceManager().getCurrentReactContext()
        .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
        .emit("notificationClickHandle", map);
    } catch (Exception  e) {
    Log.e("SuperLog", "Caught Exception: " + e.getMessage());
    }
  }

}
`

**Comment by viscardo** [comment]
I am having the same issue

**Comment by c-info** [comment]
having same issue, service stop after few minutes on back press

**Comment by viscardo** [comment]
I realized that any error on my code during the background service make it crash. I recommend you guys using sentry to log  errors and then you can find a way to fix it.

**Comment by RiccardoCafa** [comment]
You could try implementing a bound service instead of Foreground, I think it shouldn't stop, tho I've didn't found this information on documentation, it's likely to work in that way.
https://developer.android.com/guide/components/services
