### ISSUE TITLE
No task registered for key myTaskName

### ISSUE THREAD

**Issue by DwsCode88** [Raja0sama/rn-foreground-service#22]
I keep getting 'No task registered for key myTaskName'

Where is that coming from??

**Comment by VonJie** [comment]
i have the same error, how to fix it?

**Comment by Raja0sama** [comment]
Kindly before opening up an issue, go through the example that I have written and attached in the docs.

**Comment by jokertrip** [comment]
I have the same error and I don't understand why it is. Read the docs a thousand times

**Comment by saumyabhatnagar2000** [comment]
When the foreground service is not running, then only this

> I have the same error and I don't understand why it is. Read the docs a thousand times



> I have the same error and I don't understand why it is. Read the docs a thousand times



> I have the same error and I don't understand why it is. Read the docs a thousand times

When the foreground service is not running, then only this warning is coming.

**Comment by saumyabhatnagar2000** [comment]
> Kindly before opening up an issue, go through the example that I have written and attached in the docs.



> Kindly before opening up an issue, go through the example that I have written and attached in the docs.



> Kindly before opening up an issue, go through the example that I have written and attached in the docs.

When the foreground service is not running, then only this warning is coming up.

**Comment by saumyabhatnagar2000** [comment]
> I have the same error and I don't understand why it is. Read the docs a thousand times

Have you registered the ForegroundService in index.js ?

**Comment by thtRajasthaniGuy** [comment]
+1

**Comment by Elozino** [comment]
```
import ReactNativeForegroundService from '@supersami/rn-foreground-service';
ReactNativeForegroundService.register();
```

for anyone coming in the future with the same error, add this to your `index.js` file.

Thanks @Raja0sama for the awesome work
