### ISSUE TITLE
Android notification icon issue (Resolved)

### ISSUE THREAD

**Issue by rollsroyc3** [Raja0sama/rn-foreground-service#27]
Had the white square icon issue for notifications..
https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/

Finally after trying different icons, I looked at the code and noticed on index.js that icon should default to ic_notification.
` * @property {string} icon - Small icon name | ic_notification`

But if you look further down on line 186 it's set to   `icon = 'ic_launcher',` . Since this image isnt transparent or the right size, we get the white square.

So easy fix for PR, or you can just pass the icon value when calling start..

**Comment by ahmedbhesaniya97** [comment]
Generated PR for same
https://github.com/Raja0sama/rn-foreground-service/pull/28

**Comment by iarmankhan** [comment]
Check my PR for this
#36
