### ISSUE TITLE
Task :supersami_rn-foreground-service:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by etessari** [Raja0sama/rn-foreground-service#3]
I have installed the package on my project which is based on expo bare workflow.
The build with:
`yarn android`
fail with the output:
`error: duplicate class: com.supersami.foregroundservice.BuildConfig`

Am I missing something?

**Comment by Raja0sama** [comment]
Hi, I have never tested it on Expo, I really can't help at the moment.

**Comment by imAunAbbas** [comment]
@etessari I was facing the same issue. In my case, I always use the react-native dependencies without its `^` sign. This thing restricts the Node to not update the packages even with the minor changes. I simply placed all `^` signs back to the dependencies in the `package.json` file. Then I deleted the `yarn.lock` OR `package-lock.json` file and `node_modules` folder. Rebuild the project and my project was running successfully.
