### ISSUE TITLE
Error: ForegroundService: Foreground service failed to start.

### ISSUE THREAD

**Issue by amduffy19** [Raja0sama/rn-foreground-service#34]
I created a new react app and set up this library using the instructions [here](https://javascript.plainenglish.io/react-native-foreground-service-f7fc8e617fba). When I run it I get the error "Error: ForegroundService: Foreground service failed to start." Any idea what the problem is?

**Comment by Raja0sama** [comment]
Amanda try the foreground service example.

**Comment by amduffy19** [comment]
I cloned the example repo and that works. But I need to be able to run it on my own app -- are there any steps missing?

**Comment by amduffy19** [comment]
Figured it out -- I had a typo in the service declaration in AndroidManifest. 🤦‍♀️
