### ISSUE TITLE
Doesn't work on React-Native 0.68.0+

### ISSUE THREAD

**Issue by Camillebzd** [Raja0sama/rn-foreground-service#35]
Hey,

I tried to install and use this lib on a fresh react-native project in version 0.68.0. After following all the installation and try to call it, the only thing that happened was : "Start Service Triggered". No error during the build or while the app run. 

I tried to install it again 3 times, then I tried on another new project under react-native version 0.67.0. Surprise, this time everything work correctly...

So I can confirm that the service work for react-native 0.67.0 and bellow but not for 0.68.0+.

To reproduce it, it's very simple :
react-native init newproject --version 0.68.0
yarn add @supersami/rn-foreground-service 
-> follow the step in the README or [here](https://javascript.plainenglish.io/react-native-foreground-service-f7fc8e617fba)

**Comment by CrifQui** [comment]
i have the same issue

**Comment by osama-kwanso** [comment]
Same. Anyone found the solution?

**Comment by Gopinath-dartexon** [comment]
Facing issue with Android 12

**Comment by Raja0sama** [comment]
Working on my end, posted a new version, check if it helps
