### ISSUE TITLE
Stops working in background after a while

### ISSUE THREAD

**Issue by dogukan9** [Raja0sama/rn-foreground-service#46]
Hi everyone. everything works fine on emulator but when ı test with my phsycal device it stop to print console  after 10-15 seconds later. How to fix this?

**Comment by Raja0sama** [comment]
Test it again, i just posted a new version.

**Comment by dogukan9** [comment]
@Raja0sama  Is there a way to make it work without changing the battery settings?

**Comment by Raja0sama** [comment]
Actually, no @dogukan9, Your mobile phone is trying to save battery, probably not the stock android, trying to save up some ram and stuff and killing the application in the process. So to answer your question, no.
