### ISSUE TITLE
Inquires: Changes in Delay

### ISSUE THREAD

**Issue by dejongyeong** [Raja0sama/rn-foreground-service#5]
Hi @Raja0sama, first of all, thanks for the incredible work.

I would like to inquire, would it be possible to alter the "delay" time based on certain conditions when the foreground task has been started?. For example, if the user is within the geofencing, change the delay from 30 minutes to 15 minutes without stopping the task?

Thanks. Looking forward to hearing back from you.

Best regards,
DJ

**Comment by Raja0sama** [comment]
Hi, there are two types of delay supported, one is by javascript thread and another one is by JAVA thread, Create a simple non-interval-based task and inside of it create your own javascript based interval and with the listener, you can clear the interval and reinitialize a new one programmatically.

**Comment by dejongyeong** [comment]
Hi @Raja0sama, thanks for the comment. Can you elaborate more on that as I couldn't figure out how to implement what you have described. Any modifications needed on the JAVA side or just on the JAVASCRIPT side? Thanks. Much appreciated if you could share the pseudocode or a snapshot of how can it be implemented. Thanks 😄 much appreciated it.

**Comment by panshulyogesh** [comment]
can you implement a background service
?
or peobably give me a idea on the same

**Comment by Raja0sama** [comment]
When you add a task, you define what kind of task it is going to be, by providing options like loop and delay, that if the task is going call itself after a certain interval, besides that you can always start a task and set up an interval by using set interval and that will work the same way.

**Comment by panshulyogesh** [comment]
Hi I am using usestates in my foreground service and it crashes saying
there is a memory leak in my program when app is killed any idea why?

**Comment by Raja0sama** [comment]
Why would you update the state like that, it wont work. The thread in which
headless task work is independent of the react native thread, meaning you
can update state from the task.

**Comment by Raja0sama** [comment]
Cant*

**Comment by panshulyogesh** [comment]
Yes I understood that both thread shouldn't be merged!! Let's say..I have
foreground task which goes for fetch api every 30 seconds and if there are
any messages it gives a notification using
react-native-push-notification.now when I press on the notification the
same message displayed on screen.

my problem is the fetch api url changes every 30 seconds so the message
displayed should also change every 30 seconds how can I implement this.?

**Comment by Raja0sama** [comment]
You can try saving the message that u fetched from api in local storage and
upon clicking on the notification the first component that mount fetches
local storage data and display.

**Comment by panshulyogesh** [comment]
Thanks !!
My final doubt is does this foreground service run when device reboots ? I
cannot test this since I am using a emulator. or should I add anything else
to run this foreground service on reboot ..

**Comment by Raja0sama** [comment]
It wont work if you are using some kind of custom android version, it will
work if you have given permissions in stock android.

**Comment by panshulyogesh** [comment]
Thanks ,
permission which I have given in android manifest file right ? The ones
which you've specified .
