### ISSUE TITLE
Notification icon background color

### ISSUE THREAD

**Issue by matheusyuri7** [Raja0sama/rn-foreground-service#54]
Is it possible to change the icon background color? I would like to change that green if possible

![WhatsApp Image 2023-01-03 at 10 52 47 AM](https://user-images.githubusercontent.com/41174454/210378083-95dafc13-98b3-4c13-9a34-4db366ed744a.jpeg)

**Comment by Raja0sama** [comment]
Duplicate of https://github.com/Raja0sama/rn-foreground-service/issues/55.

Feature pushed and published
