### ISSUE TITLE
My task stops running with app closed after some time

### ISSUE THREAD

**Issue by Mynameisjohndev** [Raja0sama/rn-foreground-service#64]
Initially I put a hello world just for testing, over time I was doing tests and I came across that when the app is closed the task stops running. I intend to improve the task so that it captures the location of my user and stores it in the local database, but as I said, the task closes after a while, is there any way to keep it longer?

my code: 

```
useEffect(() => {
    ReactNativeForegroundService.start({
      id: 1,
      icon: "ic_launcher",
      title: "Meta Coleta",
      message: "Você esta fazendo uma coleta com a meta \n🚚 Estamos te acompanhando durante o trajeto!"
    });

    ReactNativeForegroundService.add_task(
      async () => {
        console.log("Olá mundo!");
      },
      {
        delay: 20 * 1000,
        onLoop: true,
        taskId: '12',
      },
    );
  }, [])
```

**Comment by Mynameisjohndev** [comment]
Yes, it appears, but as I said, after a while of running the task, it closes by itself

**Comment by Raja0sama** [comment]
Okay, if you are using a physical device and a non stock android, that is
probably the reason because a non stock android do their own in app
optimization, basically kills the inactive or seems inactive app after a
while to save up battery and ram.

**Comment by Mynameisjohndev** [comment]
Yes, I thought about that possibility, but isn't there any way to keep the application with priority so that it keeps running the task?

**Comment by Raja0sama** [comment]
You show warning like most apps do.

**Comment by Mynameisjohndev** [comment]
Show an alert that this task can close or what, I don't understand the reason for showing it, could you explain better?
