### ISSUE TITLE
Notification appears but task is not executed.

### ISSUE THREAD

**Issue by farhan-spinny** [Raja0sama/rn-foreground-service#65]
Hi,

This is my code.

```
import ReactNativeForegroundService from '@supersami/rn-foreground-service';

const addTask = () => {
  ReactNativeForegroundService.add_task(
    () => {
      someFunction();
    },
    {
      delay: 0,
      onLoop: false,
      taskId: 'taskId',
    }
  );
};
const execute = () => {
  const executionStatus = getExecutionStatus(); // from local storage
  if (!ReactNativeForegroundService.is_running()) {
    // if service is not running, add task & start service
    addTask();
    ReactNativeForegroundService.start({
      id: 1,
      title: 'Started',
      message: 'task started',
      icon: 'ic_launcher',
      largeIcon: 'ic_launcher',
    });
  } else if (executionStatus) {
    // if service is running and execution status is true, do nothing.
  } else {
    // if service is running and execution status is false, update notification and add task
    // sometimes the service is stuck here. Notification appears but the task is not executed.
    // ReactNativeForegroundService.is_running() returns true meaning service is running but adding task does nothing. Calling start again says "Foreground service is already running." but the added task is not executed.
    ReactNativeForegroundService.update({
      id: 1,
      title: 'Resumed',
      message: 'in progress',
      icon: 'ic_launcher',
      largeIcon: 'ic_launcher',
    });
    addTask();
  }
};

function someFunction() {
  setExecution(true); // stored in localstorage
  if (someError) {
    ReactNativeForegroundService.update({
      id: 1,
      title: 'failed',
      message: `failure : ${someError.message}`,
      icon: 'error',
      largeIcon: 'error',
    });
    setExecution(false); // stored in localstorage
    return;
  }
  // long running code
  // ...
  // in the end
  setExecution(false);
  ReactNativeForegroundService.stop();
}

<Button title="start" onPress={execute} />;
```

This works perfectly for 99% of the time. Sometimes the service is just stuck.
It is stuck in the update block. mentioned in the code.

Please help me understand the issue.
@Raja0sama

**Comment by Raja0sama** [comment]
Okay, From the looks of it, The task is there; you need to register a new task or remove the existing task and add another one with the same id; also, you need to register the task before the update code, so headless tasks queue have some tasks to work on. 

```
 addTask();
 ReactNativeForegroundService.update({
      id: 1,
      title: 'Resumed',
      message: 'in progress',
      icon: 'ic_launcher',
      largeIcon: 'ic_launcher',
    });
```
You can remove the task that is done using `remove_task`  as well. 

Also, we have another function that can update the task `update_task `; you can try with that as well and let me know if this helps.

**Comment by DevHamzaShahid** [comment]
> Okay, From the looks of it, The task is there; you need to register a new task or remove the existing task and add another one with the same id; also, you need to register the task before the update code, so headless tasks queue have some tasks to work on.
> 
> ```
>  addTask();
>  ReactNativeForegroundService.update({
>       id: 1,
>       title: 'Resumed',
>       message: 'in progress',
>       icon: 'ic_launcher',
>       largeIcon: 'ic_launcher',
>     });
> ```
> 
> You can remove the task that is done using `remove_task` as well.
> 
> Also, we have another function that can update the task `update_task `; you can try with that as well and let me know if this helps.

Hi @Raja0sama , i have implemented this task everything is working fine like even while app is killed it is still fetching location, thanks for that but problem is that after 2 or 3 or sometimes after 5 minutes this task stops even notification still exists at the top.
 I am registering this task in my index.js file i.e: ReactNativeForegroundService.register(); and starting this task from particular screen i.e: 

ReactNativeForegroundService.start({
        id: 144,
        title: "Started",
        message: " task started",
      });
 and stopping this task using 
ReactNativeForegroundService.stop()

Everything is working fine but after sometime task stops and notification still persist at the top(notification removes when ReactNativeForegroundService.stop() called).

i just need help to continue this task until unless user stop this task using this command ReactNativeForegroundService.stop().

i hope you understand my problem and suggest me something where i am  doing wrong.

thanks ❤️ .
