### ISSUE TITLE
App crashes when in background

### ISSUE THREAD

**Issue by PrernaBudhraja** [Raja0sama/rn-foreground-service#67]
Fatal Exception: android.app.BackgroundServiceStartNotAllowedException
Not allowed to start service Intent app is in background

How can I resolve this? I am already on the latest version.

**Comment by Raja0sama** [comment]
Permission Required, make sure you are running the post-install script

**Comment by zidniryi** [comment]
Already but still error.

**Comment by suman379** [comment]
Go to setting -> Battery -> Select your app -> Select anything apart from restricted mode.
