### ISSUE TITLE
Task Stops After Few Minutes

### ISSUE THREAD

**Issue by DevHamzaShahid** [Raja0sama/rn-foreground-service#69]
Hi @Raja0sama , i have implemented this task everything is working fine like even while app is killed it is still fetching location, thanks for that but problem is that after 2 or 3 or sometimes after 5 minutes this task stops even notification still exists at the top, it also happens sometimes when device is locked but for that i have used wakelock too 
<uses-permission android:name="android.permission.WAKE_LOCK" />
while device is locked it works for nearly 30 seconds or little more.

I am registering this task in my index.js file i.e: ReactNativeForegroundService.register(); and starting this task from particular screen i.e:

ReactNativeForegroundService.start({
id: 144,
title: "Started",
message: " task started",
});
and stopping this task using
ReactNativeForegroundService.stop()

Everything is working fine but after sometime task stops and notification still persist at the top(notification removes when ReactNativeForegroundService.stop() called).

i just need help to continue this task until unless user stop this task using this command ReactNativeForegroundService.stop().

i hope you understand my problem and suggest me something where i am doing wrong.

thanks ❤️ .

**Comment by Raja0sama** [comment]
Then just run an independent headless task instead of using the service-dependent one.

**Comment by h1nson** [comment]
@Raja0sama What the 'independdent headless task' mean?
