### ISSUE TITLE
Not able to remove Sticky Title programmatically

### ISSUE THREAD

**Issue by riyasolanki** [Raja0sama/rn-foreground-service#7]
![device-2021-03-23-115200](https://user-images.githubusercontent.com/21073880/112102715-b1f3c980-8bce-11eb-8a22-4a2a34d10862.png)

Can we hide the sticky notification? And also work foreground service.

**Comment by Raja0sama** [comment]
No, that itself is a foreground notification and because of it, android lets you run your headless task in the background.
