### ISSUE TITLE
Notification tab is not show in Android 12 or above versions

### ISSUE THREAD

**Issue by ksrajath7** [Raja0sama/rn-foreground-service#73]

**Comment by ksrajath7** [comment]
The notification tab is not closable on drag in Android 9 as expected.

I am able to successfully run the task in background with the same app in Android 9

The issue with respect to Android 13 is the notification tab is closable in Android 13

**Comment by ksrajath7** [comment]
https://github.com/Raja0sama/rn-foreground-service/assets/27329467/bf790631-eaf3-43a3-991d-03e795549983

In Android 9 , working perfectly as expected

**Comment by ksrajath7** [comment]
https://github.com/Raja0sama/rn-foreground-service/assets/27329467/3404a558-eae9-4e77-9c82-5f4d65b5ce5c

In Android 13

**Comment by Raja0sama** [comment]
I will investigate.

**Comment by Santosl2** [comment]
This is a expected behavior...

See in https://developer.android.com/guide/components/foreground-services#user-dismiss-notification

![image](https://github.com/Raja0sama/rn-foreground-service/assets/67132916/36ed7c73-46c8-4050-9c1f-2501c0a38f83)

**Comment by SurajMohanty02** [comment]
I can't see the notification in Android 13

**Comment by ksrajath7** [comment]
@SurajMohanty02  Check if the notification permission is enabled.

Alternatively i am using another package react-native-background-actions and it is working for me

**Comment by SurajMohanty02** [comment]
Manage Notification was off by default

**Comment by SB2318** [comment]
How can you do this man? Please recover the issues for Android 13. The library is too good.

**Comment by FazilMuhammed** [comment]
any Update ?? Please recover the issues for Android 13

**Comment by ksrajath7** [comment]
@FazilMuhammed  @SB2318 @SurajMohanty02 
Alternatively i am using a package react-native-background-actions and it is working for me

**Comment by SB2318** [comment]
> @FazilMuhammed @SB2318 @SurajMohanty02 Alternatively i am using a package react-native-background-actions and it is working for me

@ksrajath7  previously I have also tried with react-native-background-actions. But it is a background service. If we need to handle very specific condition like Doze mode, it will not work. For Doze mode I need a foreground service which is compatible with android 13 also. can you please help me by providing some information regarding the resources.

**Comment by Raja0sama** [comment]
Hello Everyone, I just was able to run this on an Android with the Android 13 version. Seems like you need a new permission to show a notification, which is 

```
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
```

Please try again after adding this. Furthermore, below is an example application via which I was able to run the application. 

https://github.com/Raja0sama/foreground-service-example

Please feel free report back.

**Comment by Raja0sama** [comment]
In Addition, you can use libraries like React Native Permission to request permission from the users. Permission required moving forward by user. 

https://www.npmjs.com/package/react-native-permissions

**Comment by dev-abhinavsinghHP** [comment]
Hi @Raja0sama I add this Line <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/> 
But not getting Notification in Android Version 13 it is working fine in Android Version 11
