### ISSUE TITLE
How to get data from foreground service on app resume?

### ISSUE THREAD

**Issue by Jurpp** [Raja0sama/rn-foreground-service#8]
Hi! First of all thanks a lot for this library, it works very well!
I am using the library to scan for BLE devices when the application is in the background (with the ble-plx library).
I do something like this to start add the task:

`ReactNativeForegroundService.add_task(
    () => BackgroundScan(device_list), taskOptions);`
 
In which I pass an array of devices to scan for. When the application is resumed (or reopened by tapping on the foreground service) I would like to pass an array to React Native containing the devices that remain to be found.
So:
- Create ForegroundService with device_list = ['x','y','z']
- App goes to background
- App finds 'x' and 'z'
- App resumes, ['y'] is passed to the react native layer.

Could you tell me if this is possible, and if so, give an example of how to implement this?

**Comment by Raja0sama** [comment]
You can use the async storage, Mark the devices found in the async storage and when the app is resumed, recheck from the async storage, for the devices that are yet to find.

**Comment by Jurpp** [comment]
This is a great solution, thanks a lot!
