### ISSUE TITLE
Notification not working, but process is running

### ISSUE THREAD

**Issue by Perry1207** [Raja0sama/rn-foreground-service#87]
I followed the installation video and added the following solution to run the app: https://github.com/Raja0sama/rn-foreground-service/issues/86#issuecomment-1920907971

After that I got the foreground process running when presing a button. When closing the app the proccess kept running so that is working good. But I've not gotten the notification on my android phone.

**Comment by zju1** [comment]
Permission is given, but still not showing a notification.
